### ISSUE TITLE
support dynamic feature registration/unregistration

### ISSUE THREAD

**Issue by nadako** [vshaxe/language-server-protocol-haxe#4]
not needed right now, but might be useful in future. it also means binding `*RegistrationOptions` types as type params to request/notification method instances.

**Comment by Gama11** [comment]
I think this should be supported now. At least I'm using it here:

https://github.com/vshaxe/haxe-languageserver/blob/9a56226d3d77c7ed016e6d0b0f6bde12972ec079/src/haxeLanguageServer/Context.hx#L301-L315
